<script>
import { onMount, getContext} from 'svelte';
import { slide, fade } from 'svelte/transition';
import { address, contract, provider, nfts, balances } from '../store';
import { Swiper, SwiperSlide } from 'swiper/svelte';
import "swiper/css/pagination"
import Card from "../cards/dex.svelte"


    //Help import data from opensea and pass into SwiperSlide <3 
    import { 
        initProvider,
    } from '../utils.js';
import 'swiper/css';
async function connectEthProvider(reconnect=false) {
    if(!$address) {
        await initProvider(app, reconnect);
        $address = $address;
    }
}import SwiperCore, {
  Pagination
} from 'swiper';

// install Swiper modules
SwiperCore.use([Pagination]);


function connectWallet(event) {
    connectEthProvider(false);
}   
var metadata = {
     "name": "SpacePepesFTM",
     "description": "STRINGS",
     "image": 'https://spacepepes.com/pepes/',
     "external_url": 'https://spacepepes.com/pepes/'
};
</script>

<main>
  <section class="fw first">
    <div class="constraint hero">
      <h1 class="hero-h1">STRINGS</h1>
      <p style="text-transform:uppercase;font-weight:100;letter-spacing:2px;">5,555 Unique Yielding NFTs</p>
      <div class="button-row">
        <button>MINT<img src="/imgs/plus.svg" class="buttonicon" alt=""></button>
        <button>STAKE<img src="/imgs/inside.svg" class="buttonicon" alt=""></button>
      </div>
    </div>
    <img src="/imgs/wave.svg" class="herobottom" alt="">
<iframe class="stringhero" src="/strings.html" frameborder="0"></iframe>  
</section>
<section class="second">

    <div class="container">
      <div class="image-text-row">
      <div class="box2">
        <p style="font-size:3rem;font-weight:bold;">What are Strings?</p>
        <p>Strings are a series of 5,555 unique collectible NFT's with proof of ownership stored on the Ethereum blockchain. 
          <br><br>This collection is an artistic depiction of how type 1 strings propagate through space and time.
          <br><br><b>Strings are the first NFT collection to be backed by their own accumulative automated yield fund. </b> <br>
          <br>SThe Strings collection was designed to provide a long-term consistent yield to holders who stake. Keep reading to understand how this yield is generated and how it will be constantly growing.</p>
        </div> 
      </div> 

      <div class="image-text-row">      
        <img src="/imgs/wind(2).svg" alt="" class="box-img">

      <div class="box3">
        <p style="font-size:3rem;font-weight:bold;">A new class of NFTs</p>
        <p>All Strings NFTs have the ability to be staked and receive rewards. These rewards are generated by seeding the sFund (smart contract) with the ETH raised from the mint event. The sFund's contracts are designed to generate yield from external yield aggregators such as yearn, curve or convex, and then reward yields to Strings stakers in the form of RENA. </p>
        </div> 
      </div> 
      
      <div class="image-text-row">
        <div class="box3">
        <p style="font-size:3rem;font-weight:bold;">The sFund's Acummulative Nature</p>
        <p>All Strings NFTs have a 5% royalty on Opensea, meaning that each time a String is bought or sold this 5% is taken from the sale in the form of ETH. (Opensea royalties are rewarded once per month.)  

          <br>
          <br>
          This royalty allows for improved yields for stakers and growth of the sFund. The distribution of the royalty fee is as follows:
          <br>
          - 3% is accumulated by the sFund, allowing it to grow over time and generate more total yield.  
          <br>
          - 2% is swapped for RENA on Uniswap and then rewarded to Strings stakers. These RENA rewards would be distributed throughout the month following royalties collection.
          <br>
          <br>
          The sFund is accumulative. The base APY for each staked String NFT should increase over time.   </p>
      </div>        
      <img src="/imgs/yarn-ball.svg" alt="" class="box-img">

    </div>
    <div class="image-text-row">
      <img src="/imgs/reuse-water.svg" alt="" class="box-img">

      <div class="box3">
        <p style="font-size:3rem;font-weight:bold;">Staking a Strings NFT</p>
        <p>Each staked String is eligible to a share of yield relative to the total strings staked. This means that if a user stakes 100 Strings NFTs and there is a total of 1,000 Strings staked in the contract at the time, this user will be earning 10% of the total yields.
<br><br>
          All of the yields generated are first swapped for RENA on Uniswap before being rewarded to stakers. RENA is the native utility token of the Strings NFT collection and is designed to thrive with high trading volume.  </p>
      </div>

</div>

</section>
<section class="third">
  <img src="/imgs/arrowbottom.svg" alt="" class="arrowtop">
  <div class="constraint"> 
    <p style="font-size:3rem;font-weight:bold;">Attributes and Rarities Showcase</p>
<div class="attribute-list-wrapper">
    
  <div class="attribute-wrapper">
    <div class="attribute-image">
      <img src="/imgs/number.gif" style="width:256px;" alt="">
    </div>
    <div class="attribute-list">
      <p style="font-size:3rem;font-weight:bold;margin:unset;">Number Of Strings</p>
      <p>Single: 100 (1.8%) <br>
        Double: 5,255 (94.6%) <br>
        Triple: 200 (3.6%)</p>
    </div>
  </div>
  <div class="attribute-wrapper">
    <div class="attribute-image">
      <img src="/imgs/color.gif" style="width:256px;" alt="">
    </div>
    <div class="attribute-list">
      <p style="font-size:3rem;font-weight:bold;margin:unset;">Color</p>
      <p>White: 111 (2%) <br>
        Teal: 222 (4%) <br>
        Red: 444 (8%) <br>
        Purple: 666 (12%) <br>
        Pink: 777 (14%) <br>
        Green: 999 (18%) <br>
        Yellow: 1111 (20%) <br>
        Blue: 1225 (22%)</p>
    </div>
  </div>
  <div class="attribute-wrapper">
    <div class="attribute-image">
      <img src="/imgs/type.gif" style="width:256px;" alt="">
    </div>
    <div class="attribute-list">
      <p style="font-size:3rem;font-weight:bold;margin:unset;">Type</p>
      <p>Tubular: 200 (3.6%) <br>
        Disconnecting: 555 (10%) <br>
        Cartoon: 800 (14.4%) <br>
        Wobbly: 1000 (18%) <br>
        Reversed: 1000 (18%) <br>
        Basic: 2000 (36%)</p>
    </div>
  </div>
  <div class="attribute-wrapper">
    <div class="attribute-image">
      <img src="/imgs/effect.gif" style="width:256px;" alt="">
    </div>
    <div class="attribute-list">
      <p style="font-size:3rem;font-weight:bold;margin:unset;">Effect</p>
      <p>Tri Morph: 222 (4%) <br>
        Doubled: 333 (6%) <br>
        Slowmo: 407 (7.3%) <br>
        Soundwave: 629 (11.3%) <br>
        Electrify: 740 (13.3%) <br>
        Xray: 962 (17.3%) <br>
        Glow: 1074 (19.4%) <br>
        Basic: 1188 (21.4%)</p>
    </div>
  </div>
  <div class="attribute-wrapper">
    <div class="attribute-image">
      <img src="/imgs/background.gif" style="width:256px;" alt="">
    </div>
    <div class="attribute-list">
      <p style="font-size:3rem;font-weight:bold;margin:unset;">Background</p>
      <p>Glitch: 300 (5.4%) <br>
        Dark: 700 (12.6%) <br>
        Clouded: 1755 (31.6%) <br>
        Basic Black: 2800 (50.4%)</p>
    </div>
  </div>

  </div>
  </div>
</section>
<section class="fourth">
  <img src="/imgs/footer.svg" alt="" class="arrowtop">
  <div class="constraint"> 
   
  <footer><div class="nav-links">
    <a target="_blank" href="https://twitter.com/spacepepes"><img width="64px" style="filter:invert(1);" src="/imgs/twitter.png" alt="">
    </a>
    <a target="_blank" href="https://discord.gg/5WrhVV5vJA"><img width="64px" style="filter:invert(1);" src="/imgs/discord.png" alt="">
        </a>
    <a target="_blank" href="https://discord.gg/5WrhVV5vJA"><img width="64px" style="filter:invert(1);" src="/imgs/medium.svg" alt="">
        </a>
    <a target="_blank" href="https://discord.gg/5WrhVV5vJA"><img width="64px" style="filter:invert(1);" src="/imgs/telegram.svg" alt="">
        </a>
  </div>
<h1>STRINGS</h1></footer>
  </div>
</section>
</main>

<style type="text/scss">
  .constraint{padding-top:6rem;margin:auto;width:1024px;max-width:calc(100% - 3rem);padding-left:1.5rem;padding-right:1.5rem;}
  .fw{}
  @keyframes glow{
    0%{		text-shadow: 2px 2px 2px rgba(0, 162, 255, 0.5), 2px -2px 5px rgba(255, 208, 0, 0.5), -2px 2px 2px  rgba(255, 0, 0, 0.5);
}   50%{		text-shadow: 2px -2px 5px rgba(0, 162, 255, 0.5), -2px 2px 0px rgba(255, 208, 0, 0.5), 2px -2px 5px  rgba(255, 0, 0, 0.5);
}   100%{		text-shadow: 2px 2px 2px rgba(0, 162, 255, 0.5), 2px -2px 5px rgba(255, 208, 0, 0.5), -2px 2px 2px  rgba(255, 0, 0, 0.5);
}
  }
  .box-img{width: 30%;      margin:2rem;
}
@media screen and (max-width:900px){
  .box3 {
      border-radius: 20px;
      margin:2rem;
      color:#333;
      width: calc(100% - 3rem)!important;
      min-height:280px;
      text-align:left;
        height: auto;
       
      /*animation: anime 3s cubic-bezier(0.16, 1, 0.3, 1) 1s infinite alternate;*/
      /* animation-fill-mode: forwards; */
    }
    .attribute-wrapper{width: 320px!important;}
  .attribute-list{
    position:relative;
    z-index:2;
    margin-left:0px!important;
    margin-top:156px!important;
    padding:1rem;
    border-left:1px solid black;
    padding-bottom:0px!important;
    padding-top:128px!important;
    height: min-content;
  }
  .image-text-row{
    display:flex;
    flex-flow:column!important;
    justify-content:space-between;
  }
  .image-text-row > img{margin:auto;margin-top:2rem;}
  .image-text-row:nth-child(odd){flex-flow:wrap-reverse!important;}
}
  .buttonicon{margin-left:1.5rem;height:20px;width:20px;filter:invert(1);}
  .hero-h1{margin-top:unset;animation:glow 5s ease infinite;font-size: 7vw; letter-spacing:4px;margin-bottom:unset;}
  .hero{z-index:5;width:1024px;margin:auto;position:relative;}
  .stringhero{position:absolute;left:0px;top:0px;overflow:hidden;width:100vw;height:100%;min-height:100vh;}
  .first{display:flex;height:100vh;margin-top: calc(-100px - 2rem);}
  .second{background:#f0f0f0;margin:unset;}
  .third{background:#BABABA;}
  .fourth{background:#222;}
  .box > h1{margin:unset!important;text-align:left;color:#555;}
  .box > p{text-align:left;color:#555;
  }
  .attribute-image > img{border-radius: 2rem;
overflow: hidden;}
  .attribute-list-wrapper{
    display:flex;
    flex-flow:wrap;
    justify-content:center;
    padding-bottom:6rem;}
  .attribute-wrapper{
    display: flex;
    width:512px;
    min-height:300px;
    text-align:left;
    margin:1rem 0rem;
  }
  .attribute-image{
    pointer-events:none;
    position:absolute;
    z-index:1;
    padding:1rem;
    width:calc(256px + 2rem);
    display:flex;
    flex-flow:wrap;
    justify-content:center;
    height:calc(256px + 2rem);
    background:#0a0a0a;
    border-radius:256px;
    overflow:hidden;
  }
  .attribute-list{
    position:relative;
    z-index:2;
    margin-left:128px;
    padding:1rem;
    height: min-content;
  }
  .image-text-row{
    display:flex;
    flex-flow:row;
    justify-content:space-between;
  }
  .image-text-row > img{filter:invert(0.2);}
  .button-row{display:flex;flex-flow:wrap;justify-content: center;}
  button > img{transition:all 0.2s ease;}
  button{font-weight:400;margin:1rem; min-width:150px;}
  button:hover > img{filter:invert(0);}
.nav-links{display:flex;flex-flow:row;justify-content:space-around;}
.nav-links > a{margin:1rem;transition:transform 0.2s ease;}
.icon-box > a{margin:1rem;transition:transform 0.2s ease;}
.nav-links > a:hover{transform:scale(1.1);}
.icon-box > a:hover{transform:scale(1.1);}
  .herobottom{position: absolute;
bottom: -10px;
width: 105vw;
z-index: 8;
left: -3vw;} 
.arrowtop{position: relative;
top: -10px;
width: 105vw;
z-index: 8;
left: -5vw;}
    .container {padding-bottom:6rem;padding-top:3rem;
      background: #f0f0f0;
      box-sizing: border-box;
      display: flex;
      flex-flow:wrap;
      justify-content: flex-start;
      align-items: center;
      width: 100%;
      margin:auto;
      max-width:1024px;
      height: auto;
    }
    section{min-height:50vh;}
    .box {
      border-radius: 20px;
      padding:2rem;
      margin:2rem;
      color:#333;
      width: 480px;
      min-height:280px;
        height: auto;
        background: #fafafa;
        box-shadow:  40px 40px 40px #cccccc,
                     0 0 0 #ffffff,
                     0 0 0 #cccccc inset,
                     2px 2px 2px #ffffff inset;
      /*animation: anime 3s cubic-bezier(0.16, 1, 0.3, 1) 1s infinite alternate;*/
      /* animation-fill-mode: forwards; */
    }.box2 {
      border-radius: 20px;
      margin:2rem;
      color:#333;
      width: 100%;
      min-height:512px;
      text-align:left;
        height: auto;
       
      /*animation: anime 3s cubic-bezier(0.16, 1, 0.3, 1) 1s infinite alternate;*/
      /* animation-fill-mode: forwards; */
    }.box3 {
      border-radius: 20px;
      margin:2rem;
      color:#333;
      width: 70%;
      min-height:280px;
      text-align:left;
        height: auto;
       
      /*animation: anime 3s cubic-bezier(0.16, 1, 0.3, 1) 1s infinite alternate;*/
      /* animation-fill-mode: forwards; */
    }

    @keyframes anime {
      0% {
        width: 60px;
        height: 60px;
        background: #f0f0f0;
        box-shadow:  0 0 0 #cccccc,
                     0 0 0 #ffffff,
                      10px 10px 10px #cccccc inset,
                      -10px -10px 10px #ffffff inset;
      }
      25% {
        width: 60px;
        height: 60px;
        background: #f8f8f8;
        box-shadow:  10px 10px 10px #cccccc,
                     10px 10px 10px #ffffff,
                     0 0 0 #cccccc inset,
                     0 0 0 #ffffff inset;
      }
      50% {
        width: 60px;
        height: 240px;
        background: #f8f8f8;
        box-shadow:  10px 10px 10px #cccccc,
                     10px 10px 10px #ffffff,
                     0 0 0 #cccccc inset,
                     0 0 0 #ffffff inset;
      }
      100% {
        width: 480px;
        height: 240px;
        background: #fafafa;
        box-shadow:  40px 40px 40px #cccccc,
                     0 0 0 #ffffff,
                     0 0 0 #cccccc inset,
                     2px 2px 2px #ffffff inset;
      }
      }
</style>
